name: Publish python-37

on:
  push:
    branches:
      - main

env:
  BUILD_PATH: cuda-python37
  IMAGE: piercefreeman/cuda-python37

jobs:
  push_to_registry:
    name: Push to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to DockerHub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build container
        run: |
          docker build --tag "$IMAGE:${GITHUB_SHA::7}" $BUILD_PATH
          docker tag "$IMAGE:${GITHUB_SHA::7}" "$IMAGE:latest"

      - name: Publish to DockerHub
        run: |-
          docker push "$IMAGE:latest"
