name: Publish python-37

#on:
#  push:
#    branches:
#      - main
on: [push]

env:
  BUILD_PATH: cuda-python3
  IMAGE: piercefreeman/cuda-python37

jobs:
  push_to_registry:
    name: Push to DockerHub
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7.7, 3.10.7]
        cuda: [9.0-base-ubuntu16.04, 11.4.0-base-ubuntu20.04]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to DockerHub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.BUILD_PATH }}
          build-args: |
            CUDA_BASE=${{ matrix.cuda }}
            PYTHON_VERSION=${{ matrix.python }}
          push: true
          tags: ${{ env.IMAGE }}:${{ matrix.cuda }}-${{ matrix.python }}
