name: Publish headfull-chromium

#on:
#  push:
#    branches:
#      - main
on: push

env:
  PLAYWRIGHT_VERSION: "1.25.1"
  BUILD_PATH: headfull-chromium
  IMAGE: piercefreeman/headfull-chromium

jobs:
  push_to_registry:
    name: Push to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to DockerHub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build container
        run: |
          docker build --tag "$IMAGE:${GITHUB_SHA::7}" -e PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION $BUILD_PATH
          docker tag "$IMAGE:${GITHUB_SHA::7}" "$IMAGE:$PLAYWRIGHT_VERSION"

      - name: Publish to DockerHub
        run: |-
          docker push "$IMAGE:$PLAYWRIGHT_VERSION
