name: Publish headfull-chromium

#on:
#  push:
#    branches:
#      - main
on: [push]

env:
  PLAYWRIGHT_VERSION: "1.25.1"
  BUILD_PATH: headfull-chromium
  IMAGE: piercefreeman/headfull-chromium
  ARCHITECTURES: linux/arm64,linux/amd64

jobs:
  push_to_registry:
    name: Push to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to DockerHub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Unlike on OSX with Docker Desktop, a builder is not setup by default. We need this
      # for downstream buildx tasks.
      # We first need to setup binfmt to support arm64 builds
      - name: Setup buildx builder
        run: |
          docker run --rm --privileged linuxkit/binfmt@a17941b47f5cb262638cfb49ffc59ac5ac2bf334-amd64
          docker buildx create --name cibuilder
          docker buildx use cibuilder
          docker buildx inspect --bootstrap

      - name: Build container
        run: |
          docker buildx build --tag "$IMAGE:${GITHUB_SHA::7}" --build-arg PLAYWRIGHT_VERSION="$PLAYWRIGHT_VERSION" -o type=image --platform="$ARCHITECTURES" $BUILD_PATH
          docker tag "$IMAGE:${GITHUB_SHA::7}" "$IMAGE:$PLAYWRIGHT_VERSION"

      - name: Publish to DockerHub
        run: |-
          docker push "$IMAGE:$PLAYWRIGHT_VERSION"
