name: Publish maturin-builder

on:
  push:
    branches:
      - main

env:
  BUILD_PATH: maturin-builder
  IMAGE: piercefreeman/maturin-builder
  ARCHITECTURES: linux/arm64,linux/amd64

jobs:
  push_readme:
    name: Push DockerHub README
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - uses: piercefreeman/actions/dockerhub-description@main
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.IMAGE }}
          short-description: "Run chromium in docker like it's another desktop app"
          readme-filepath: ${{ env.BUILD_PATH }}/README.md

  push_to_registry:
    strategy:
      matrix:
        python: ["3.11", "3.12"]

    name: Push to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Unlike on OSX with Docker Desktop, a builder is not setup by default. We need this
      # for downstream buildx tasks.
      # We first need to setup binfmt to support arm64 builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          build-args: |
            PYTHON_VERSION=${{ matrix.python }}
          context: ${{ env.BUILD_PATH }}
          platforms: ${{ env.ARCHITECTURES }}
          push: true
          tags: ${{ env.IMAGE }}:${{ matrix.python }}
